var QUESTS=[
 {key:"m1-osnovy",icon:"🧭",rec:true,title:"Основы продуктового мышления",promise:"Из чего складывается продуктовое мышление — от мотивации человека до метрики продукта",desc:"Как JTBD объясняет зачем, MVP — насколько дорого ошибиться, а build trap поджидает тех, кто забыл об обоих.",n:7,slugs:["jtbd","jtbd-christensen","mvp","build-trap","product-market-fit","north-star-metric","engagement"]},
 {key:"m2-cena",icon:"⚖️",rec:false,title:"Цена и ценность",promise:"Цена — конструкция в голове, а не число на экране",desc:"Как опорная точка, привязка и боль платежа управляют воспринимаемой стоимостью.",n:8,slugs:["reference-point","anchoring","prospect-theory","loss-aversion","loss-aversion-critique","mental-accounting","payment-pain","decoy-effect"]},
 {key:"m3-vnimanie",icon:"🧠",rec:false,title:"Внимание и состояние",promise:"Внимание — не ресурс",desc:"Почему продукт ломается в реальном контексте.",n:8,slugs:["cognitive-load-theory","miller-law","system-1-2","attention-residue","scarcity-mindset","scarcity-critique","present-bias","flow"]},
 {key:"m4-privychka",icon:"🔄",rec:false,title:"Привычка и удержание",promise:"Что превращает разовое действие в рутину",desc:"Петля повторного использования.",n:8,slugs:["habit-loop","fogg-behavior-model","operant-conditioning"]},
 {key:"m5-socialnoe",icon:"🪞",rec:false,title:"Социальное и идентичность",promise:"Решение редко принимается в одиночестве",desc:"Социальное давление.",n:7,slugs:["social-proof","bandwagon-effect","social-identity"]},
 {key:"m6-doverie",icon:"🔗",rec:false,title:"Доверие и сбои",promise:"Доверие строится годами",desc:"Психологический контракт.",n:8,slugs:["source-credibility","trust-calibration","peak-end-rule"]},
 {key:"m7-temnye",icon:"🔦",rec:false,title:"Тёмные паттерны",promise:"Как их видеть до того, как они ударят",desc:"Цена тёмных паттернов.",n:7,slugs:["sludge","partition-pricing","fomo"]},
 {key:"m8-metriki",icon:"📊",rec:false,title:"Метрики честно",promise:"Когда метрика становится целью",desc:"Закон Гудхарта.",n:7,slugs:["north-star-metric","aarrr-funnel","goodharts-law"]}
];
var TITLES={jtbd:"JTBD — Jobs To Be Done",mvp:"MVP",engagement:"Вовлечённость",anchoring:"Якорение","loss-aversion":"Неприятие потерь","cognitive-load-theory":"Теория когнитивной нагрузки"};
var SEEDCARD={jtbd:{lead:"Люди «нанимают» продукт, чтобы продвинуться в своей жизненной ситуации.",apply:"Спрашивай не «что добавить», а «какую работу пользователь пытается сделать»."}};
function esc(s){return String(s==null?"":s).replace(/[&<>"]/g,function(c){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c];});}
function mins(n){return '~'+Math.max(5,Math.round(n*3))+' мин';}
function titleOf(s){return TITLES[s]||s.replace(/-/g,' ');}
function isTwist(s){return /critique|critic|contra/i.test(s);}
var qs=new URLSearchParams(location.search);
var QKEY=qs.get('quest'),STOP=qs.get('stop')?parseInt(qs.get('stop'),10):null;
function quest(k){return QUESTS.filter(function(q){return q.key===k;})[0];}
function renderHub(){document.getElementById('nav').style.display='';var feat=QUESTS.filter(function(q){return q.rec;})[0]||QUESTS[0];var rest=QUESTS.filter(function(q){return q.key!==feat.key;});var H='<div class="bar"><div class="bt">Квесты</div></div><div class="head"><div class="kick">Учись через истории</div><div class="h1">Расти</div><div class="sub">Ведомые маршруты по идеям.</div></div><div class="feat" data-q="'+feat.key+'"><div class="ti">'+esc(feat.title)+'</div><div class="pr">'+esc(feat.promise)+'</div></div><div class="seclbl">Все маршруты</div>';H+=rest.map(function(q){return '<div class="rc" data-q="'+q.key+'"><div class="t">'+esc(q.title)+'</div><div class="p">'+esc(q.promise)+'</div></div>';}).join('');document.getElementById('wrap').innerHTML=H;bindQ();}
function renderDetail(q){document.getElementById('nav').style.display='';var H='<div class="coldq">'+esc(q.promise)+'</div><div class="ddesc">'+esc(q.desc)+'</div>';document.getElementById('wrap').innerHTML=H;document.getElementById('overlay').innerHTML='<div class="start"><button id="startBtn">Начать квест →</button></div>';document.getElementById('startBtn').onclick=function(){location.href='quests.html?quest='+q.key+'&stop=0';};bindQ();}
function renderPlayer(q,stop){document.getElementById('nav').style.display='none';document.getElementById('overlay').innerHTML='';var M=q.slugs.length;if(stop===0){document.getElementById('wrap').innerHTML='';document.getElementById('overlay').innerHTML='<div class="cold"><div class="cq">'+esc(q.promise)+'</div><button id="go">Начать →</button></div>';document.getElementById('go').onclick=function(){location.href='quests.html?quest='+q.key+'&stop=1';};return;}if(stop>M){document.getElementById('wrap').innerHTML='<div class="fin"><h2>Квест пройден</h2><p>'+esc(q.title)+'</p></div>';return;}var slug=q.slugs[stop-1];var H='<div class="pc">Остановка '+stop+' из '+M+'</div><div id="stopwrap"></div>';document.getElementById('wrap').innerHTML=H;var sc=SEEDCARD[slug];function paintCard(title,lead,apply){document.getElementById('stopwrap').innerHTML='<div class="stopcard"><h2>'+esc(title)+'</h2><div class="lead">'+esc(lead)+'</div></div><button onclick="location.href=\'quests.html?quest='+q.key+'&stop='+(stop+1)+'\'">Дальше →</button>';}paintCard(titleOf(slug),sc?sc.lead:'',sc?sc.apply:'');if(!sc&&window.__livecard)window.__livecard(slug,paintCard);}
function bindQ(){Array.prototype.forEach.call(document.querySelectorAll('[data-q]'),function(el){el.onclick=function(){location.href='quests.html?quest='+el.getAttribute('data-q');};});}
if(QKEY&&quest(QKEY)){if(STOP!==null)renderPlayer(quest(QKEY),STOP);else renderDetail(quest(QKEY));}else renderHub();
